# Generated by Django 5.1.2 on 2025-03-28 17:12

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('organiser', models.TextField(max_length=20)),
                ('venue', models.TextField(max_length=20, null=True)),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime(2025, 3, 28, 22, 42, 23, 447515), null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.datetime(2025, 3, 28, 22, 42, 23, 447515), null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('recurrence', models.TextField(choices=[('N', 'None'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=220)),
                ('recur_start', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('recur_end', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
