# Generated by Django 5.1.2 on 2025-03-28 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 28, 22, 52, 35, 221612), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 28, 22, 52, 35, 221612), null=True),
        ),
    ]
