# Generated by Django 5.1.7 on 2025-03-28 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD'), ('MS', 'MS'), ('MBA', 'MBA'), ('M.Des', 'M.Des'), ('M.Sc', 'M.Sc'), ('MA', 'MA'), ('B.Des', 'B.Des'), ('B.Sc', 'B.Sc'), ('BA', 'BA'), ('Other', 'Other')], default='B.Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('AE', 'Aerospace Engineering'), ('BB', 'Biosciences and Bioengineering'), ('CE', 'Chemical Engineering'), ('CH', 'Chemistry'), ('CE', 'Civil Engineering'), ('CSE', 'Computer Science & Engineering'), ('ES', 'Earth Sciences'), ('EE', 'Electrical Engineering'), ('ESE', 'Energy Science and Engineering'), ('ESED', 'Environmental Science and Engineering'), ('HSS', 'Humanities & Social Science'), ('IEOR', 'Industrial Engineering & Operations Research'), ('MA', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('ME', 'Metallurgical Engineering & Materials Science'), ('PH', 'Physics'), ('IDC', 'Industrial Design Centre'), ('SOM', 'Shailesh J. Mehta School of Management'), ('Other', 'Other')], default='CE', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.TextField(default='TL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_group',
            field=models.TextField(choices=[('C', 'Club'), ('TT', 'Tech Team'), ('Co', 'Community'), ('O', 'Others')], default='club', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 0, 27, 17, 915458), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 0, 27, 17, 915458), null=True),
        ),
    ]
