# Generated by Django 5.1.7 on 2025-03-28 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_user_degree_user_department_user_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 0, 42, 16, 552663), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 0, 42, 16, 552663), null=True),
        ),
    ]
