# Generated by Django 5.1.7 on 2025-03-29 12:41

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[('C', 'Club'), ('TT', 'Tech Team'), ('Co', 'Community'), ('O', 'Others')])),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(choices=[('C', 'Club'), ('TT', 'Tech Team'), ('Co', 'Community'), ('O', 'Others')], default='club', max_length=20)),
                ('bodies', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_group',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 18, 11, 59, 206765), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 18, 11, 59, 206765), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='body',
            field=models.ManyToManyField(to='events.body'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.ManyToManyField(to='events.usercategory'),
        ),
    ]
