# Generated by Django 5.1.7 on 2025-03-29 14:29

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('C', 'Club'), ('TT', 'Tech Team'), ('Co', 'Community'), ('O', 'Others')], default='C', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_category',
        ),
        migrations.RemoveField(
            model_name='body',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='posted_by',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.user'),
        ),
        migrations.AlterField(
            model_name='body',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='body',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='body',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 19, 59, 43, 417230), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.body'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 19, 59, 43, 417230), null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='body',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('AE', 'Aerospace Engineering'), ('BB', 'Biosciences and Bioengineering'), ('ChE', 'Chemical Engineering'), ('CH', 'Chemistry'), ('CE', 'Civil Engineering'), ('CSE', 'Computer Science & Engineering'), ('ES', 'Earth Sciences'), ('EE', 'Electrical Engineering'), ('ESE', 'Energy Science and Engineering'), ('ESED', 'Environmental Science and Engineering'), ('HSS', 'Humanities & Social Science'), ('IEOR', 'Industrial Engineering & Operations Research'), ('MA', 'Mathematics'), ('ME', 'Mechanical Engineering'), ('ME', 'Metallurgical Engineering & Materials Science'), ('PH', 'Physics'), ('IDC', 'Industrial Design Centre'), ('SOM', 'Shailesh J. Mehta School of Management'), ('Other', 'Other')], default='CE', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='body',
            name='category',
            field=models.ForeignKey(default='C', on_delete=django.db.models.deletion.CASCADE, related_name='bodies', to='events.bodycategory'),
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.AddField(
            model_name='user',
            name='body',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.body'),
        ),
    ]
