# Generated by Django 5.1.7 on 2025-03-29 14:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_bodycategory_remove_user_user_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 20, 0, 57, 920812), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='posted_by',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 20, 0, 57, 920812), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.body'),
        ),
    ]
