# Generated by Django 5.1.7 on 2025-03-29 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_end_time_alter_event_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 20, 1, 48, 448246), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 20, 1, 48, 448246), null=True),
        ),
    ]
