# Generated by Django 5.1.7 on 2025-03-29 14:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_end_time_alter_event_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 20, 4, 17, 594727), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 3, 29, 20, 4, 17, 594727), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.body'),
        ),
    ]
